AWSTemplateFormatVersion: '2010-09-09'
Description: Setup Amazon EKS Cluster with Resources and Outputs

Parameters:
  ClusterName:
    Default: otel-demo
    Description: The name of the EKS Cluster.
    Type: String
  ClusterSecurityGroupId:
    Description: The security group ID for the EKS control plane.
    Type: String
  AllSubnetsIDs:
    Description: A list of subnet IDs to use for the EKS Cluster.
    Type: CommaDelimitedList
  VpcId:
    Description: The ID of the VPC for the EKS Cluster.
    Type: String

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
      Tags:
        - Key: Name
          Value: otel-demo-eks-cluster-role

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      AccessConfig:
        AuthenticationMode: API_AND_CONFIG_MAP
      RoleArn: !GetAtt EKSClusterRole.Arn
      Version: '1.31'
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ClusterSecurityGroupId
        SubnetIds: !Ref AllSubnetsIDs
      Tags:
        - Key: Project
          Value: otel-demo
        - Key: Environment
          Value: production

Outputs:
  ClusterName:
    Description: EKS Cluster Name
    Value: !Ref ClusterName

  ClusterEndpoint:
    Description: API Server Endpoint for the Cluster
    Value: !GetAtt EKSCluster.Endpoint

  ClusterRoleArn:
    Description: IAM Role ARN for the EKS Cluster
    Value: !GetAtt EKSClusterRole.Arn
