global: {}

route:
  receiver: default-receiver
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: default-receiver
    sns_configs:
      - topic_arn: arn:aws:sns:us-east-1:445567080751:prometheus-pod-alert-topic:0b6a3eed-24b4-40c0-a0f4-a831adf31cca
        sigv4:
          region: us-east-1
        subject: "Prometheus Alert: {{ .CommonAnnotations.summary }}"
        message: '{{ template "default.message" . }}'
